---
apiVersion: v1
kind: Namespace
metadata:
  name: mld
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mld
  namespace: mld
---
# NOTE: I'm speedrunning and bumping into:
# Bucket/mld/mld-rds-backups dry-run failed (Forbidden): buckets.s3.aws.crossplane.io "mld-rds-backups" is forbidden: User "system:serviceaccount:mld:mld" cannot patch resource "buckets" in API group "s3.aws.crossplane.io" at the cluster scope
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mld
  namespace: mld
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mld
  namespace: mld
roleRef:
  kind: ClusterRole
  name: mld
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: mld
    namespace: mld
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github
  namespace: mld
spec:
  itemPath: "vaults/kubernetes/items/github"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dockerhub
  namespace: mld
spec:
  itemPath: "vaults/kubernetes/items/dockerhub"
type: kubernetes.io/dockerconfigjson
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mld
  namespace: mld
spec:
  interval: 1m0s
  secretRef:
    name: github
  url: https://github.com/jfreeland/mldegrees.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mld
  namespace: mld
spec:
  interval: 1m0s
  path: ./deploy/prod
  prune: true
  serviceAccountName: mld
  sourceRef:
    kind: GitRepository
    name: mld
  targetNamespace: mld
