---
apiVersion: v1
kind: Namespace
metadata:
  name: mld
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mld
  namespace: mld
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mld
  namespace: mld
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mld
  namespace: mld
roleRef:
  kind: Role
  name: mld
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: mld
    namespace: mld
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: github
  namespace: mld
spec:
  encryptedData:
    password: AgCxko6NPagGmr4rD26ZAOygGHH8Q76LxbW87cKkkGJj4hhFCri0F9EskkxrSQMtxGJaSclyXYNC/HVFpEHQNGu+F5omCYFM/xMORPs5vyX6VsryRtGd61QCb8Gn3F7Xnyh6UB9EiHs/sU18Eokja/vSVL1HjJdtVZa8sr3+u59+Q423TJ1bKoJg+BRgFmbbvUyRgiunmzMIcnnaM0civ66pn3i0/I8l+R1tpW7sqfwpJJRVR4Yy544o6IrEs9NHdIU8VXTQCXOqReFevHWOOuTbFA43gCAD8RKqQwcfBsru4lr4cmc2mVCNsjibxGzZwF5HoRTUULL7mGB1Vfd2f6WV7gm3sBEbluUMZDTK9zmG4g4o6AnppkoG7ch0ATY3z8hewxnNaApvCop4n2BarIKP5TBqgkAY9Clufpal+VnZkKacn8ySIes8T9MuyxRRz4cCAj6b2gwwATwaxfvvuSjhgtBN5FIV6CxR/mmr4yRdp7G5WQ8CNOu0BArAJkW6KMXlQNoR0xxiBLXa6DDCL1g1xu+j30avzEWgZrjI/gpqX57dlSqqrPKh1kvGERIcqk2Xh3cHOvQjUU1ygqwFnyhpRp8GdxxjlZy8ZM7/ZSFDfH7qW9Q/ItK+QaN5xTQd0R8YQwIEmMunoZD05NQHPVUVuhzmJHuwZqolL0C3g7OO8+O+vYiOyv6xoqFRcA6pDZV3HI7uq7gySonnU/8f3+BKD3gF9KCAEirOzQe3PpOOPDJZCPfWZOjM
    username: AgACjWKMbipjtwYIKYvaFKYrq/UQ82TCDPYCZQbKOSS0s3NkQYNyWBqX7t6l1TnUSzNXdZP1mM2686jAVVczhYcS54E3Feq/H2ZKQsbY5vTJW0oJisPKhLjEPN6/VyRc+Cwg2zL0Y+iTi4zcb1fIcI4jn3QqBTsNJvusEaFRgkBGGPWk/jBSPwGa886thLbuErgLhhIIiVKUuzyS0RVhYT3v9Wy6G4pcCwKrQsk0z/VheVh8dT2ml1X3ifSXDhUDgq142OEV9DyO0inyWn3Ul4iK0kYrP6z/0Qo7WlXxO1+XLcX6U2sHBbakU1IqiQX1piJN+ijjVD6FPC+HV0YhxDDVLHlbYsT44xjBX0felCBl2wBqhsDCh0rwJhvUKC4g8GQKAgbKoqhoya4ewSTY6Dnd/kaE2oX5tnAuouF7qO5uWKXWRAAQ3C6XDqzl5T/4QobUurFJ5FwCWCLatUcKyxnyc4ITM5De9YFLfLG/Yg1u7MLjabKYYe/VcFCQetpIW4KyAMxTncxEZFLsRJwhDE67dMVcsKI03JjAtzZA6Xb8ZqGFONEkA8vHlahs4wnNQD+Fyjy5CTLUeLl9uWV0IfNqF538Ua/q9S2JwMdUVTeKPEXmnEvG7yfAjG6RMTIyybGKUXCfiLo8OIKN6I/QyNkcWX/5hV8K3FXM+AFSBrc/zNrqnXR7Y1nIBmuWLA+0Rfe5TJGp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: github
      namespace: mld
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: dockerhub
  namespace: mld
spec:
  encryptedData:
    dockerconfigjson.json: AgCcQCQcQf8CiPHkwDx+odURb3G4m1mUkGmc5mAZtlPEnHTe6K7hWR4wF7iACfPOzwajKdp68NNSrkesl912xivmoloJjhBZ5oVVNNOLb1xffiBuyK4k6qKeXEII9jm+M6Tu8BTyLQD1Ykwocnppv/6gkU7B2l0PdQw7BA9cGhLmV469nUXA5ZZEa8cgrrqG82XWQYHSzvoqjQthboLcZTXvbnA/WJz0aneo6BW/8Ulmmt8Js/uMKZmFvNBrfeGvboIwFVcTxyJ1pao1xjGACD0+Fd8dAkgl/IbWfIYoG8FIY/aC9nKqrAsuGBA5noGRsz2CFY7IG/3rYpaMrSED7uMjDi2RR0AhuqmDXgrr+BwTkLvYN5Snj1rBqS95ZyrZrDLQ7U5bMaSf7vtSECuvcgPDG6P92BcypFxqk7jrJ2+/fQpUMZq7GvJSsoVNGYzeDGL6qCog+EkjL+vLtPSC+g9nxfGBQ+iy8aDvV69+ZP/8c8pS1WQYYUkzEoN1Yxwd2ROGu0+sHX27izJJ499UFmevEmuKvBTCEDeGxUW9aoSICGT6X6lS1EElzWKGPW8AHKRrhih7fT/tEA//R0BlIc6ZME+KFIhlejAXr0HL+P3AnAH4ctg4Pf2W0O5us2vvit9vFwIwLpbzc+go+9CKGgXRO8Del7hOsj+po+T2AMto25+P8+WhyRjcjQsVvRX9QmO+Nem56qrz34CacWgUyW+sTrLyafhNoku6Big12Jh8Fu5a+GGnAK63QLYjRQsaaRjTvLEer9v2cvV5M2xBJfBlu/ve48q9rmtaFusid8Rt26LDYpHsrjksats+68c9fApRDjPhmrWkI3YGZdOBh+P8SyPBhPv5nkVGypVhng==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: dockerhub
      namespace: mld
    type: kubernetes.io/dockerconfigjson
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mld
  namespace: mld
spec:
  interval: 1m0s
  secretRef:
    name: github
  url: https://github.com/jfreeland/mldegrees.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mld
  namespace: mld
spec:
  interval: 1m0s
  path: ./deploy/prod
  prune: true
  serviceAccountName: mld
  sourceRef:
    kind: GitRepository
    name: mld
  targetNamespace: mld
