---
apiVersion: v1
kind: Namespace
metadata:
  name: prepare
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prepare
  namespace: prepare
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prepare
  namespace: prepare
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prepare
  namespace: prepare
roleRef:
  kind: ClusterRole
  name: prepare
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: prepare
    namespace: prepare
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github
  namespace: prepare
spec:
  itemPath: "vaults/kubernetes/items/github"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dockerhub
  namespace: prepare
spec:
  itemPath: "vaults/kubernetes/items/dockerhub"
type: kubernetes.io/dockerconfigjson
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: prepare
  namespace: prepare
spec:
  interval: 1m0s
  secretRef:
    name: github
  url: https://github.com/jfreeland/prepare.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prepare
  namespace: prepare
spec:
  interval: 1m0s
  path: ./deploy/prod
  prune: true
  serviceAccountName: prepare
  sourceRef:
    kind: GitRepository
    name: prepare
  targetNamespace: prepare
