apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 5m
  path: ./elastic
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
  dependsOn:
    - name: infra
      namespace: flux-system
