# https://github.com/1Password/connect-helm-charts/tree/main/charts/connect
# https://artifacthub.io/packages/helm/onepassword-connect/connect
---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: 1password
#---
#apiVersion: bitnami.com/v1alpha1
#kind: SealedSecret
#metadata:
#  annotations:
#    sealedsecrets.bitnami.com/cluster-wide: "true"
#  name: onepassword-token
#  namespace: 1password
#spec:
#  encryptedData:
#    token: AgCGQxeCZ0SZDwkaBA6Arz37wz3ZftPziBb0pzh6Nw1xnTtGCAcECUkU/qxL5UeQ7Cvcjx5BnbCjrzV2qSgZ19oA2K+gczcBV8orpBvzeZ64n1ncw25T1QrIjjsvu904P2+v4su6ozP8E3rfLaYeTHQAf/7oqTscCfBs5TAgtP+hmNyH0oWMOvzZA8OhbCG1Kp5i38vkw/2UmwsGT9jnXv6R3MC7sxRAcMFBKC0+ugyW8Ky+H1S0Nio2AHi3prq9U/CXArGfox8/UQXm7+lt/qEkK0tOd+y6vLVw0lfIOQeTTntm6btiZO4WLH10QqQt/Oox88a7RhR81YpEGsUB2yhrRCNFDa/I4O8P9BgFm8/j58TZK5MXgQ5ogntHmIUwdEkr7LFvupDNBFqaVLt012a2wfFqud7qcCSZg09G8yc4ah7sUMZCRAECcqm9mFQZTHvnKWSb0ZLZ6h6E66Uf4OzNKYz6TMABXE3IgizESorTiUNvHy4glXeQKjLzInvJrnwyzODZuro/+U7rN0UOcdNzp1OUBrsJNnLEcbj0NyMPgpQmJqY8A9B++OKUWxLH/AFYi3YutzjztGLUhSJLBpn3573ImagetCouFoMQLgFi2hhobNbN2dfNAoHfp4q8DPe2CbE24jfARuK9+fAz/jq4oadu5mMQSkusb+kwcLhNw2lbvOQwcyDGDX8cjy1PhJHLC3JIm7JcasuSiOsPERhMudRMshacNKEsSC6D7IrNVSC1/iv5EUq9PM+TgybW5ZdDNML32eBahMRPPQGt8gj/mQDGeoQa1MHdqwO3rhIEbi83Zxz6AWwDA1rpmkmY/FAzp6UHbZ0yHH5rMsJh4vVSb1idLe3eGOb023DmTCrgmAwbIhxD86y00Kve7AtxFyeDmDTzZWVCzjOEeF/PEmwwNtSpeurZpUzse/NDS51/usActDVQyH7sUF5K8ScN6Cm913nQvW7iUqhRoVb8UPv6K5KEyKZ9eZRQQMGqHe9xM4Img36w9OHp+JmXr2hM1f7oe73nXY3YQwgdqR/uB6EKdsVenVo21uXLkNY7aJzp51W5DvVQmpCUqbU6rIx1KQt1IokMLzJ+jBmxIyUbRNS3O0Z3jAQ7kHy7RqmEE3O9WgwmOLT5wVvDwAf7CNJ/3zN0TKlTfIEONGX0KBOPxd0NOhaQjMj930wr3S0MLx8AzJGNn9cm51+aKDon6aAgrjKT3pXDgEE1wAhA6eY5x0AoQEdfGHHxFWAptjwTPFAQ/gnbpe5PNJ9vPzkbCKWgxe74l19qU4hhCAHXIihR+45h6JKN3U0Ctmgmrn70cv8J0pzv5Khe9aXPiWx2LxnM5TKflqBCwCWYZVzN/W9Yym/jgPwg2RPRX1v8lFsk0qBvroZVFxv3d+JNGfiZHo6PPxIUYooM57PiTgRla7bwXU0kQ2+l0OooGxNZLgFW6pdbBx7fqChHnIIS5h585xC8KQcFl2bpInSPPtGxZH2Uw2F9t9uhOXcvyI8tSn+QUeSHJsiixKb/YnzD+trgibks7NvUTXEtypkH5bYu//WpFqDxwjg=
#  template:
#    metadata:
#      annotations:
#        sealedsecrets.bitnami.com/cluster-wide: "true"
#      name: onepassword-token
#      namespace: 1password
#    type: Opaque
#---
#apiVersion: bitnami.com/v1alpha1
#kind: SealedSecret
#metadata:
#  annotations:
#    sealedsecrets.bitnami.com/cluster-wide: "true"
#  name: op-credentials
#  namespace: 1password
#spec:
#  encryptedData:
#    1password-credentials.json: AgBMZBlrB7E+k+fpaMx3YGNHd1/HexgJMW3R2oaSkIaJag6n9bS5MsNmuvjufnuYvHU7M7szcV9fMHHMaPW3fQKr7u5CrWrfjox8Xe9WXulCUU7SLvlawu2BO7AlyTZO0mIzNr0rpPphCVHJVozqfCdYp0IZ25No+PEKPd+aXsorVh5EXtW7W6iRHfaoYp648oSaHSESL36Byk8Plm1iDi14N+Q2GfzUgQsY0DBQ5EB66zL1deHnwSNFkzceBpsL1/uFHCWPPMs2gKPmXTIcyQvu94uaiG2fjWF0gouw0pKqaP4LKy4xzyhrFC72iNvRV+4yCI43w0jB7EYkcfiYFEkHRNkQVMoiPxlcf+ddcYMMi28B1VwKoM0Ztf1wMA5gEvcdpoEcUvV+ut9Lbfqm/WdDBEb5YI2wWfs5IFCQwanA0qrYzO7ysOpC8VYJ0xEzqA1pMGqQlYIQbEMPGLImqQG+EieiYHr9uHKkJ3bxTMNe6yAAb2JT392zuekxtP7vDBXDCcV9JgSw7eY0iKFUB3/JZ9SN9wAngn3p1G6syrPeYEFFSizzoQq42fjR+ULRNQWq9rzDHfFs8YHi/jRBuR33UBxb20aZmHGQOKcBRWgtZy5SB0CwfuC8IXjeBup9NVhoGGqsHy0xjZVyg6y/aPaltvUIsEzm/WWwxiLABm5mz2pWf6T+8tl9c/sQIoLhMvtHYcnwq7oOyy80gwVhHunDBzoQGj3yqO7yhc9NGPLDc8efLGsv3ATdo/g7NroYnG2mQE+islVclsNQlBD2qBKtQMfogklD+UkfJrmvRKOrgnDpCMewr3+ga26PsQQR9Ojh59Cyvg9kxRQOupwk9Sseo+PSK2XpbEyYQbjh1itcUA57l0XzOoRsnaT3DpMoJ65zLl8mwLDUpMFzMEzrRCSNecWRq3FvMCuIz8K28aJuGwgk5FE0u1PcDFkefzKnc0dKQH5kIJX6bi9VwaVaBg063s4UXzltuH9P+wxy5mBkkZsoFR+ZorH+qniSkAfXRDetzWk2QdOQouseDqQR1a0wh04Uu+PhVyUo0kanxd9aYxIrS47+3+uH7bgPsoSfCxiINuCgBNVujlV36EULXGn9/2KYYORTPjDGLCMDLLHRBJ5weDgDkQy4mSakG376gXm7SJqKbOCKQ5wYdTVg6ApiWapj/1hVOgnnTHlHPI89sVlMqNsja24iNXwiRlGeneuHkzG6nID6opV43+ARQkSXinEfJVfVKwNw+WJDMB4dyCv0q6r6F7SiB97lpDNmD8csevZmq9htdVSg0sYN1rsqn7zUJEdBiIaq86F2CZaqU1Zbtz0vdNK73YhDX1MSwoi7oQ+Pb1fCUulTfBAzVaBLdBgUtcT6UrD6Wt0+q/kJGiQltFsobyftewxAfVbBebeZn1WFA62xYpvYQatSouJMmAmLTMYLXC8xpBwpg9RpbRqV/zsZGlRclTJ/qcA1qggO8HSenh7PXEAB2cokc1i/Lxv3BPsFeGPuyA/LK05s4mUUS16oJw27iPsKAw7eBTca+wQLlnewkiWSVUHSrBT1hyc5Aaj2fXrkCgGD4vEuCXhK1o+utJHZlbi+prNp5ihUojyLFusTse83iwsIUxjFQfTHO4lz+lERMW5SWz1lj2HrynZVkE3qN1mVg/se0T6pGd6JGCJrzlq0J9PYpaq8fve3XOk/PIVWPMe8DFZf/+9au3ZicxVh5S3rOXWdNSrmhzuXpyb6nRXPXQPSUhCw7JOrGrE+TcqmktdL89kHwQwd5DDbvNLPJ+cSy3vZ5xKkHawEyXftqEuMWkTxuTF8YfdTVNYGeTL0/Tl83K/apBGDUc6x3W6guGCj+JkfQOkfAgoQP9HsvthnQGYDc/uXNM0Fm3B2xD0xE1T7OcMvQrw9b6q4bXjIYrSd5SzoZ4fwhx8WsZkRUcePD8dw7HfMG4H8cWcgSlcCDPWN/Wp/LB+o2wcrtJFJvoDYyvhNgfz+Q8+82mrmpCJ4wK763l0rtZbhDVuh7VHQLJ0OdcgNkrYj0dd+eRTd9gpx5DW/cn5342dxyTLqJ9Zw/9QouDA8mAsYNsQnizAbcDOJ7P67pYMARfpX/MGstuAAUgneTdW78VnFpDQR0yYEUk9h7DxLADDGTB0zbZf+qI2RLa2D0TeGhrCXQebtkADhIDczMONNiKBhUtZ1ebGQkKWodOiQJ/r23/9Mc/wG8B++1J7Wz8Tbmd6HJtui8miRGZVFybMxT1yDb4tumHDk8BqNfVpnu4jFmKCbeSQdtpscvLQ+HsXHxS6UYaM0mmHT6mSAWJgieEgAODNUFD5ws2yoqeiDvILMa00rv4hr6iswX+5ejOCNNenxouNvw+n0p/meRdz05g90y1VMcxZmI48ysl6WCEIO6kpoC8LQlf51krQmnBs/WXdKL9LTvDBAQWVbbIy3eExpGAU55fiIVi4mw/XnQflgHGTcghEWU9Qjh/PHfFnYiuhlUorpzt/plIyOjnhH8raSV7waJXrp2MI9PodDq/HA/vKS7poykPFgE9YHUdWsJsQJOYSiXVjsdyhvKFXh7TaHc3tj3aPz4h3T+xOA04hBD3LvhGc9Qy0ysbKhorfZSoWIHEnBTpo0V0a7z5BjmgB0EbQkQPe1OhQ=
#  template:
#    metadata:
#      annotations:
#        sealedsecrets.bitnami.com/cluster-wide: "true"
#      name: op-credentials
#      namespace: 1password
#    type: Opaque
#---
#apiVersion: source.toolkit.fluxcd.io/v1beta1
#kind: HelmRepository
#metadata:
#  name: 1password
#  namespace: flux-system
#spec:
#  interval: 5m
#  url: https://1password.github.io/connect-helm-charts
#---
#apiVersion: helm.toolkit.fluxcd.io/v2
#kind: HelmRelease
#metadata:
#  name: connect
#  namespace: flux-system
#spec:
#  releaseName: connect
#  targetNamespace: 1password
#  chart:
#    spec:
#      chart: connect
#      version: 1.17.1
#      sourceRef:
#        kind: HelmRepository
#        name: 1password
#  interval: 5m
#  values:
#    connect:
#      credentialsName: op-credentials
#      credentialsKey: 1password-credentials.json
#    operator:
#      create: true
#      token:
#        name: onepassword-token
#        key: token
