# https://github.com/1Password/connect-helm-charts/tree/main/charts/connect
# https://artifacthub.io/packages/helm/onepassword-connect/connect
---
apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: op-credentials
  namespace: 1password
spec:
  encryptedData:
    1password-credentials.json: AgBTnvn7hT2Z5yzHbVJJdPeYGj7AzckjgoxkKfJbvIXRK6yGeVHMZcTvmMdNaCeQ8/4TTRjaxgQBAWUw1tpPARGstPAx/BCwf623HHTSkaHfh/arP33pCa4RZH73VgX66ttI1d1qWWEXz2H4jzUqNeWp9n6ShE4yl+UBP6E1JOSajwWJaygwrxKo30V9gcveibcAIpJ5eGzoiiKkcuGvomEGCOOTTEp4ar2kW1W6zUIiuYj3FjwqtskMNJO6B8lPHM34Q2ouaeiQv54GXH8+//FH7f+1WK7eBqxnKDDCfRUs/Wr5fLFD+0I9BzKllNPWmVMIPYhDyD+ul9oyB8Vnw2CqQ7SuyluVUiIw3ElG4tWHyCIpV9aXLKSp3+wgQE+9ocItga8Tf1eoNM6XGtU9wpcf7EHbwMeEuuvt+YNCpJe9G71iz1bSeS9POdxWcNZKxBthmspzt1EEBjD6Tv8lwf8Ryuj9ZphHbhprrM5PN9WLKgC5IfIYmNfl7sQ4+Ko3YnfYlVW3sFZdR5bIJyYBrFrtmffCHUD4TCV3HGBWSdZIGT4y+Gn4vG75NJk4eqiw5thMM7DA4GiU8solFm24P43JEtFc+/qqF2FwIB4jLxTgtAc/ohHbwm3JobSyzi3EpyyaCW+783vsnboN+2vnn/XKcMLP0q5nBJ11jggHCIfjEaxcGQ2GCsVVQA/h/R4e1QvlalH8MBvJG7C2HWNegle9jAGlJtWk6g68XDZOMxwvPPDTJ8+anDc0Az6hwDjLq71brLR5whChf8L16o7TAAP81Jl/BOBK074aFvqwqIbrKM2jd95e6Hxi+Bqf7KemLSssd+DYhPN5VuBUutJmGVVSD0Z3M4ayp0FoHCn15Ipk95DPBXWY5dXKwIOXcKjwfKBKrgOZa9cuOWP+y2qlgahzeM8sXB0OavjZuYaDSsi6UpmKhkoo9dT/BZB5b1sJP33qUm0z574ebqzHs4dvm3Z8ezYb8IDFo7JjMVybQXDMvkMuVvvlLHJjEHLnaabsH8TW7xW3cSv38s//vasDU4NPzO8lMrs7uVr5GM75vIdBRQ4yP8VKbtr1sgrv30g08QDmfRhE4DHsiX8xuRU4d/nlqF5e2XYR6vAhtLu7o4MTgpsEE0gWz9xPS8BqvpspNIXETZahWP3QkCfqnsI4GwGZc5/caogPfYTaWwIEkplK+E+H3ylxcRfAbFwe7xr8QeaO8VnnaR19c+/JakXauahwB6mKlN+ukcPzu/j3eAvg38cBTdY2JXPYe1Fis/ZltMigiQn3vqWpRl2r2ZVy57fF0Xw6KjENvUDDUwzaZLRW21f6V+/n4lBPABY9lIShTpGz0pQGJzFkHOoUpmkLsmLwWP44hkZpjVosw9YWLgfDRC540wyfcu7sH7zcx3/CrwTAk5rZIWU15aKy/53cJsGttKx9FiKcAzVXDKnydT5EYl9+wa0y4Q8sPvbEVdYDG2yumOjVsUxU+to7rVUjQqzT+/6IT05LV8IeIw0svIpnx81AJNd8zU4CJjrHsAaGwbm/hF21knTZklsYKlMzdJijg9jV9WSWdkAxPZCILF1BXmrqXplMpJ654BfZflyrhPY0XiHwhWjWuZ/W+PenN0vtX1XEsA8pgRp/PyM/tXLfjP5UWRnnu49K0Vi07VXrTWPBOIAmA3gUgnn2RRW0/9HjQlr2+HCt3a+JxBeD06k2f4oWXJzipBIc+XWsbF/ePObHkSL/K/01OLtTbwoUE7bHhpwQDuscXRIY5wQkQG/r5Orjr/HMlt+SxueSnwnXd0IonGkHn7RWeiV0E7Om0LoqqNIBf0bwYzsqkChx/UnitoG3do8MT+38MG2yOBJCYVW11PxcapYd7mmgjdnuNQnHyXF/lbt57TX3YeHQgN5a7WL+eWZoH7XEc1nRDxjTK6UJkjASuuLrkrFcOKyiXb/dIRFV8XRoMr+2l7FzwpxayFDP+hBUn2oM0Hz99SpEo3/n3OYvdwGyR2HVyUVU3CHMVCPN8G+LVGnPfNgMnwWT7L5d5eQ5eTO80erI/fhsayydMT9StAnzziqnTcM2esDInWNZFd8OdjpuLTzFO8vJ3FzUzyts0qWWqObosMwRd/TLnlkpYcNNyBbaBZWSptTYt1foIC1g4qiKy2P41pgj
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: op-credentials
      namespace: 1password
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: onepassword-token
  namespace: 1password
spec:
  encryptedData:
    token: AgBEYt0XQdXp1Qtgq/PPKMKulshJkZt3B5F4beisQGHYejI5CWmh891u27UMZKFMOFrmk5b502AJr4m50dSwI430t/5oZeXmVPz0N3nKxGvUaisEwaId/skPBqBMmCwQJ2BPRMow2GH7cHGuAhYSjI8rj4NpgHp1fTEywF/MjSWkYTcvxYPnB4IAsUSMVVMXnzADcXrCpDnmOYNmNbuHenlWU1XtAOqa7/l0X+dnPL5GrYO2zmZFY0PJqm0D7x9sSO6urC88nrwDHxHgo2wC6P2RPj4Sgp3yMXALBi8DPVaPzSjWU1fNLgC3W1O1HOSOyt1jnUcGPeW8IVK/wnfQUqgyTMjxdo48B8XaET24QeMhymj4Ej/pkZ9HYrOBF7w2PgxlMIYpAjS4ENuS6K7qicL7JtI4NCFjdse/hsT0iEXXyuJNG/xCkw2aAzl/ksPHcRPGAwsF4/i/2vYhMMcyFHH1YKjzyce8VpwoXUWG66AYr2e3Ks6ZDQH1HIf42sMJg91heM36fxDJiGCCAVcIO9dQAHisEkPXR2Ilp0nb39O1GeTPsDsFEF5SOw/533J0svLaVfyaam35ZgNq0GucQu1uf3bk8+ZQS5z1D2Y5iwXegJcv5hnk0vSMF12GBJtjO02ZTU5Xf2Toymbh2qMZiyA569TJH/zocl+OGqYBhuGNqa7Fv6bfowz9Vz0KtwfPj6RYIjFOlIzO55HHMupifHqVG5YVJSnHgUnkXzediav8GEUsCOSnjdDz2ucVK0Q+91AjzSQeszUw1OQsk/DafItTNRerutK5OJYnPXeljK7fVV6+ELhfrhl+6/UZagHTBalfP8EYMAu65EXb6WzC+9sRIYJ8c5qRYmPd4A6JQlQZl94HlHH/w0PnqzPmiqHg7utsRDOOFB4zjFxiH6FsTSnQGYohZhEJ1xUU4a6D90cjdM3pu78MQGpHx2lZMWP/nD9FEDGm961h+U8cqEyGRRhMYXIEGAzf2y8Ixy5VMJR4d2KtkyqQ9kILdaNGrk+PjbmZ9yfgN8+DdQhfiEjxXuSKi9+d/7LN1OGm8I02RaM2MZvJkFmTqqqhI6lwWJmJvEIjooCdbuqHW2xdhbE3nbRA0srk2qdl0Kq9bL8HDhtd0rbUWsp0yvXR1yfwmDD+Dpo9z9b983/F+R+IyoMgsOktUWBu9fj2dyhaPLkOpsJAEHDhMcUsm/sl/QbMg4AUBHq93PbKK+gDHiE90vxjujqXrEpSmIzdwjfJbwDGEF+KA2SiPivh1ZjTJSA1ajqkPVUL4gLVfDLfYAWL3M6F0hjp7PP3Il3vB9UupP4L3Ymgv4a0S48sukJ9JKUEK1H4UMpKfrttMa68Gx0KdlmiabAvjAzd9Ypnd7jmttNU3PB0QMDu5ei0DluP3IrCX27OE28hZy7kKDUq0tx0gn/gb+Nrp+rogVXJEvzTaSvuMLEbf7DRAUw6SFvXo9yn8RMeVXXNPzkPuNaSAusns3YSm42X2RRoVz998OT1o730ej9qjVyvvfNVGtUsXCIFRfbMBO1kgKkHXxG5jZuncUkL15pO5eA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: onepassword-token
      namespace: 1password
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 5m
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
  namespace: flux-system
spec:
  releaseName: connect
  targetNamespace: 1password
  chart:
    spec:
      chart: connect
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: 1password
  interval: 5m
  values:
    connect:
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
    operator:
      create: true
      token:
        name: onepassword-token
        key: token
