# https://github.com/1Password/connect-helm-charts/tree/main/charts/connect
# https://artifacthub.io/packages/helm/onepassword-connect/connect
---
apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: op-credentials
  namespace: 1password
spec:
  encryptedData:
    1password-credentials.json: AgBdNldpWNSjEyPvSNkwlnDmUfPaW0NvoJBouBZQvpERdG6QCSVzlnJ512aXsrNyS8jtetDpfWIv5DbGeAVwbbN0Mpj6aq2gsTRuOfxX3WB2k8Ff8gq0eqZtM5jP/iTLkkxtMGczOLTHrgrDnF6ASM19D7HQSodA0s6CdHHPrHIi9pDmCH0/1bL9M/Vmn6NmP3jgFVTPQ03W83rVm1YyIsGxWK9yCO9SrbOaX3HlB7TKo77eZwqfvBqc8Nj3lOjn5OPeTDkT5NJEvlYDRv8aiqqMq4F2cRNg5zlrlYXdzKH9Wj6HQQJRSMt8lB1wbf9rWM/KhjN8+LYyUT0lYXH/G6Bfbjn1/uX1dSK9Qcj7DHIMp9w0wfhr4jox9OImAvlBSmkl9ou56FmvuyFHryQxDPwizhXNftjY9EFNifoSBmXnuXkly61XgwvFy/wwKmxkTPAL8inNit7QNf78Y2D82jBeEoqFk3UFyO6Phru4Eu1DitEXv48o27ZNyfqax+fjIViigo1xOFkJJR2RivwxZS3KptHDzXwt7W/3ahtSYhJc3nW7fi8XMG3ePXCef/rtq6N+CL7STa0A+GNcd28kUv/yUC4yYtr5zzkbDBlG9eaRKng7RwWTZgrhQjmYBJk+0FpcfFlavc9TDlh+7wfMdQTdkSyvdv/at9cZZ/vCMBindJxzK/oKo5vnpvGbxC2WY+NfHurSI3tZs6QfV92AZZ4J+fOH6Z5j+6UrNCSM/XSufj/U12PWWLsL+4H37pW1z05mNEz5v9dndxDMSnRuwxNemW1Sig2bpnQ70XU8AsKQwPD/BAUWf3A655jlZkpVdIwLTH/fQf1kGbac1GhV6BwwPTktRKkhj9EQiUPOGzqzPlf674ud8a0puzsu4DmBZUSuc69hUzsJEv18K+dTD/ZnnmmIhiuCOnlfxvDTdXwe8u+jhMivExynBeWMv2uWSKqD8LPSxb8R/rl3ubcbO+9VTJ9T9iDiJDEiFwi4K3VX+kr7AjHLNRJGasCW5VWyh6NMeY2yH9KpT7W2A850hy2QiqIbmunhXgCYNVPi5ioxsajLG4QUMtyMGT0b6kpt/9dTBSSYBCopJF3knBeK+agae9QdkzE9zR53cT5+UlHn9UBmKMj29iv/s9oXxU0v8XgFCw27C72FzP8P4zeSpfwIbaLZlfH/lr9mDh7a5/fszMtYToEK3B0v569ujbeJiQO83BTFlfckHZBqf6fi9Elyn8nxwgr2pD5PUTz2KcAo5vvLNPS9OfvX+2xFnbjfuBQXXIGswBbJrscd3cxcqNJinoLHLB/eHmRN9L+dkjtUpCVuAPfLEpTaTIZNZau28U8QQHvwx89Yi+27cr2a+zYHfch5yNGOSOVPVd4sOvEcY5hbzI4texjmwwxppiXtVfM/Y4mdQX68FjuIP/IIO0xWYn5fgIgQ+ZjdHjYohSbWNW/uOXJRYcUeq2QXAiquBuPmXujyGV2fSAECQ+AfAvseEoeW0CgVbEHDcdyPh8u52kXQCe/OrBrg9I02X9H/4QGPqIpLUjnYbuD/GLvvZiwqNB59ckahMDQTiat0Itbo3TcNqpN8PcoZ6jUXSK+f+3PaGqXgFGobpEHODXpFhG60M/rCb9lyoLyHgrytcM5S+3fj+V9ZxzSNO2fBiFgdX4qJvvNLeuuU4PFPM36PCej0lJ1gSOkWdulfFwZffG4d/IArnR5F1NuRrzq6FyiBob60mxuw6lgQVdOD4q4ZI0y/XbKZQKiCIQOMWhQs1Kx4CAo3nrG6oNXvcxjGRPaBboPFsv9p+D5NE+nQe6dUVZWYgt76e2zJwgsXgLYD2YrYqv3yhs1duRGfLQjTnRlMPpfRme5nDeBXu95auwYY+EQE7d93wiac2f96MyI5qGCa4lhunc4hM/oqO34bW3E2qBSIZsfb9zA127s38hoSUY6ze9AfAK31x+yIaQgNQ/Z8FR0OfkaI/dZrvbjafU5S0kymSsaatITZo8PQt0pX+GHdL+PNRUx2ZKpFLDmbLrnmMdU03xpfA8CMvMVnkcqaMpHTYx3OlkwhMnY1tGeDVBXKioqfmk8iKJ1vI6gyTivE73Zxphas1pJqLfwILKtZy12sEWRGhBDKBkarjdcO/xfD1vLWcrScc9VIXR6U2uFN21IPm7sdXrLsKN60k2pKcGcXSZ6RKY+6N+yJH+np6iKHUE+c3MP0/uUxWUl4YcqTaYzWAS0JShLmOuBTiUNRVTJjL04jZctL5lEmkzuhTVySL0LRdauJf8PuSlei4WMXnG46EIiT4sP68WOHA/lxXWSXiA+CzSvMK4lXZntfFg+3ZH7asXnk/9aXIFOK1i0l/gLh4uwwJEGE1TX8sNtJ4cBS3BOx0vTtNDxThHvbTd8/iYgNug+K6MTJtSG8cgtWjjiaNf8+dLZW4yAPzH9H8r47zhqSZsuAgWp2xYItF20RssU8qePpuLjT+xikDlABTQK0JgPiylFt7qWiaLoe+xP9qhr8ULHe8Dcddcxf7AVkxC5AmmwtdmSGe9HL/Hw9h8WUpWSQMjvSlqssWWhlsSbcpCGvG7QrGRglVr84CjeA6OJIfnWA9lnKYc66NYWx9XDoV9DGYDnXqbmeAFwqSrzRl0uBHKULNs/RNvMN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: op-credentials
      namespace: 1password
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: onepassword-token
  namespace: 1password
spec:
  encryptedData:
    token: AgCvLu9aYnrSgyMnF0IrMqAd/Dhj5mcG0kREAfnxNQLfihwX8PGTqbq6areyi/U+knI/7e+nSEp67s7dP2fcwwrCWFg0VBJCofMwf32e61+la11hUnW2E3FDLIie0rHttTKCRPTu0ApRcQkHsOByMRzzOn585000/ePxnys0+osNKBRTwx73DAZoyFx8mi8FKCHD2jOd4VelYTi7AORokZ9ovgANs2CTNeKggkJfi767XrJq7j/Q8JdPVv9YvRqdUnAvebZXTWNTEy8BCO22VS4Zfz0VThlfzleXvmI7wpCgxU7ZEljbgnEZpdLikuquVLdLXj5oIyzqh9DLIc8wrO0EkXDupckKXcuJhPHnS/LL4KY5rbbjAvnLgcENFJe4eNAM9VH+eul60TbRAEkLY32Q9FOWHZBYNvsgZMEcmeiacM09lwvFkiX5x/fd3DJ+eyDfHxeorHWzA141o5u7zucgvYqbOWGqHtLtc2ur+c2wlcWlJCoalpLneUomTnovk19eiqCUb8QYZx9vrpFsD8K2Tg9qXFXfI4/r6jE9ByW74hBVU4bIwBvLDkhdiQnxoRooO/PRMD/WFNyNRi+9CB1ozeMwr8/u0lXi8Ju1/H7Da6J0hkLp2beX+th1O2ThENWPOW7NmysaD7/4h8bZlrRuFZDhvpq5IP6AGlB/x+OyXrm0qlQQsSfXVxLw4SbDeomfMHwSAgLeoH69bkjLHRb+assI9FgD2KbJ4BrcLa1urbcKQCxxDcgKgvkI/OVf1m8nQExqX+DowTBuROeb2rVYOd8LZHiF7kUgtgywY9qUBDtHyrZDBXKo3Ob2I+08Iha5hc9Ob1mHj7FaleN6edD5Q0oC6peOVsAdv2rfCkhLLPnHCz9j14grrojEMzS1BOMUMnHaTGiLfd9IVVab+QOQDvdDzRmB3esSTo6TIpLcwLzEeU6dhtvLnhyyhYekFoSgO6U28Uu2ImRQSMBczNxDJo2D9ZbwqdCz4dWmn0fBGo480A0fZMP7DIccgGjcb6bpgvv5ARKnVWiXZA0j30D0LC205Z1dNGN+cjamDf2damSqGhJnoT2P2D6r1JrC7ywdnxymyuXKMy4GLIOfFl1wSEK7gAMOT3qtFrQazPfXsJGONVQDA8B/exbkoQALODasD7Y7KlCo7dbOulk2oLOaqsBAJkJNSOi2v7H/E6vZ01efJZUoo612kk0syNDLsBibmjEPn9Oq2/o0Q9YnwWikaVCZjKVz/QdcWXlNOD2gbJbjiqhwxGnMZFiWcbyi1wy/cRYApvNYtmeIXbzw2r5TzEitkJhmS9wRCRz1XolarCiYDkdj2TRX6/b8GnHdxpSPsepXq2N8263c9dKZL205xGWwNDjw+PO3OgCtw0sfjx1QtE8VyrXO2DMlf8ANjHGN/5sRNhKCFfeqBOXZ5jBXEDz6gOKbVyiJrf1U99ryenyPYaqlsVNDSneZoqHwplfD325jpFUptcaTY5X2AQ5WOu5dwZZfahbfGUZ3F6ljsIGu/Vv+oQAGG9jcEz+JiVV9DWD26Z5hU0NHVIR1ALZBTic=
  template:
    metadata:
      name: onepassword-token
      namespace: 1password
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 5m
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
  namespace: flux-system
spec:
  releaseName: connect
  targetNamespace: 1password
  chart:
    spec:
      chart: connect
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: 1password
  interval: 5m
  values:
    connect:
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
    operator:
      create: true
      token:
        name: onepassword-token
        key: token
