# https://github.com/1Password/connect-helm-charts/tree/main/charts/connect
# https://artifacthub.io/packages/helm/onepassword-connect/connect
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: 1password
#---
#apiVersion: source.toolkit.fluxcd.io/v1beta1
#kind: HelmRepository
#metadata:
#  name: 1password
#  namespace: flux-system
#spec:
#  interval: 5m
#  url: https://1password.github.io/connect-helm-charts
#---
#apiVersion: helm.toolkit.fluxcd.io/v2
#kind: HelmRelease
#metadata:
#  name: connect
#  namespace: flux-system
#spec:
#  releaseName: connect
#  targetNamespace: 1password
#  chart:
#    spec:
#      chart: connect
#      version: 1.17.1
#      sourceRef:
#        kind: HelmRepository
#        name: 1password
#  interval: 5m
#  values:
#    connect:
#      credentialsName: op-credentials
#      credentialsKey: 1password-credentials.json
#    operator:
#      create: true
#      token:
#        name: onepassword-token
#        key: token
