# https://artifacthub.io/packages/helm/cert-manager/cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 5m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  targetNamespace: kube-system
  chart:
    spec:
      chart: cert-manager
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 5m
  values:
    crds:
      enabled: true
      keep: true
    replicaCount: 1
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
