---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: test
  namespace: datadog
spec:
  itemPath: "vaults/kubernetes/items/test"
