# https://artifacthub.io/packages/helm/datadog/datadog
---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: datadog-keys
  namespace: datadog
spec:
  itemPath: "vaults/kubernetes/items/datadog"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: datadog
  namespace: flux-system
spec:
  interval: 5m
  url: https://helm.datadoghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog
  namespace: flux-system
spec:
  releaseName: datadog
  targetNamespace: datadog
  chart:
    spec:
      chart: datadog
      version: 3.120.2
      sourceRef:
        kind: HelmRepository
        name: datadog
  interval: 5m
  values:
    datadog:
      apiKeyExistingSecret: datadog-keys
      appKeyExistingSecret: datadog-keys
      clusterName: bands
      kubeStateMetricsEnabled: true
      logs:
        enabled: true
        containerCollectAll: true
      otelCollector:
        enabled: true
      helmCheck:
        enabled: true
    agents:
      image:
        tag: 7-ot-beta
