# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md#using-helm
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: external-dns-keys
  namespace: kube-system
spec:
  itemPath: "vaults/kubernetes/items/external-dns"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  targetNamespace: kube-system
  chart:
    spec:
      chart: external-dns
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
  interval: 5m
  values:
    domainFilters:
      - f6d.dev
    policy: sync
    provider:
      name: cloudflare
    sources:
      - ingress
    env:
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-keys
            key: cloudflare-api-key
      - name: CF_API_EMAIL
        value: joeyfreeland@gmail.com
